INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('INCOME_SALES', 'STEP_1', '0', 'NUM', null, 0);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('INCOME_COGS', 'STEP_1', '0', 'NUM', null, 10);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('INCOME_SGA', 'STEP_1', '0', 'NUM', null, 20);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`, `H_LEVE`) VALUES ('INCOME_EBITDA', 'STEP_1', '0', 'NUM', null, "{'required':true, 'min':0}", 30, NULL, "['INCOME_DEPRE_AMOR', 'INCOME_EBIT']", "4");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('INCOME_DEPRE_AMOR', 'STEP_1', '0', 'NUM', null, 40);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('INCOME_EBIT', 'STEP_1', '0', 'NUM', null, 50);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('INCOME_NET_INTEREST', 'STEP_1', '0', 'NUM', null, 60);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('INCOME_NET_INCOME', 'STEP_1', '0', 'NUM', null, 70);

INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('BALANCE_FIXED_ASSETS', 'STEP_2', '0', 'NUM', null, "{'required':true, 'min':0}", 0, NULL, "['BALANCE_INTANGIBLE_ASSETS', 'BALANCE_TANGIBLE_ASSETS', 'BALANCE_FINANCIAL_ASSETS']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_INTANGIBLE_ASSETS', 'STEP_2', '0', 'NUM', null, 10);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_TANGIBLE_ASSETS', 'STEP_2', '0', 'NUM', null, 20);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_FINANCIAL_ASSETS', 'STEP_2', '0', 'NUM', null, 30);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('BALANCE_CURRENT_ASSETS', 'STEP_2', '0', 'NUM', null, "{'required':true, 'min':0}", 40, NULL, "['BALANCE_STOCKS_WIP', 'BALANCE_RECEIVABLES', 'BALANCE_CASH_EQUI']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_STOCKS_WIP', 'STEP_2', '0', 'NUM', null, 50);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_RECEIVABLES', 'STEP_2', '0', 'NUM', null, 60);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_CASH_EQUI', 'STEP_2', '0', 'NUM', null, 70);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('BALANCE_TOTAL_ASSETS', 'STEP_2', '0', 'NUM', null, "{'required':true, 'min':0}", 80, NULL, "['BALANCE_CURRENT_ASSETS', 'BALANCE_FIXED_ASSETS']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_EQUITY', 'STEP_2', '0', 'NUM', null, 90);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('BALANCE_LONG_TERM_LIABILITIES', 'STEP_2', '0', 'NUM', null, "{'required':true, 'min':0}", 100, NULL, "['BALANCE_LONG_TERM_DEBT', 'BALANCE_PROVISIONS']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_LONG_TERM_DEBT', 'STEP_2', '0', 'NUM', null, 110);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_PROVISIONS', 'STEP_2', '0', 'NUM', null, 120);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('BALANCE_CURRENT_LIABILITIES', 'STEP_2', '0', 'NUM', null, "{'required':true, 'min':0}", 130, NULL, "['BALANCE_SHORT_TERM_DEBT', 'BALANCE_PAYABLES']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_SHORT_TERM_DEBT', 'STEP_2', '0', 'NUM', null, 140);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('BALANCE_PAYABLES', 'STEP_2', '0', 'NUM', null, 150);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('BALANCE_TOTAL_EQUITY_LIABILITIES', 'STEP_2', '0', 'NUM', null, "{'required':true, 'min':0}", 160, NULL, "['BALANCE_EQUITY', 'BALANCE_LONG_TERM_LIABILITIES', 'BALANCE_CURRENT_LIABILITIES']");

INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `HIDE`) VALUES ('CASH_NET_INCOME', 'STEP_1', '0', 'NUM', null, 0, 1);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `HIDE`) VALUES ('CASH_DEPRE_AMOR', 'STEP_1', '0', 'NUM', null, 10, 1);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('CASH_FFO', 'STEP_3', '0', 'NUM', null, "{'required':true, 'min':0}", 20, NULL, "['CASH_NET_INCOME', 'CASH_DEPRE_AMOR']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('CASH_CFFO', 'STEP_3', '0', 'NUM', null, 30);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('CASH_CFFI', 'STEP_3', '0', 'NUM', null, 40);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('CASH_FCF', 'STEP_3', '0', 'NUM', null, "{'required':true, 'min':0}", 50, NULL, "['CASH_CFFO', 'CASH_CFFI']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('CASH_CFFF', 'STEP_3', '0', 'NUM', null, 60);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('CASH_OTHERS', 'STEP_3', '0', 'NUM', null, 70);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `VALIDATION`, `ORDER`, `SUB_MENU`, `SUM`) VALUES ('CASH_NET_CHANGE', 'STEP_3', '0', 'NUM', null, "{'required':true, 'min':0}", 80, NULL, "['CASH_CFFF', 'CASH_OTHERS', 'CASH_FCF']");
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('CASH_DIVIDEND_PAID', 'STEP_3', '0', 'NUM', null, 90);


INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `GLOBAL`) VALUES ('FACTOR1_RELIANCE_MERCHANDISING', 'STEP_4', '1|2|3|4|5|6|7|8', 'RADIO', null, 0, 1);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `GLOBAL`) VALUES ('FACTOR1_RELIANCE_LARGEST_REGION', 'STEP_5', '1|2|3|4|5|6|7|8', 'RADIO', null, 0, 1);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `GLOBAL`) VALUES ('FACTOR1_PRIMARY_MARKET_POSITION', 'STEP_6', '1|2|3|4|5|6|7|8', 'RADIO', null, 0, 1);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `GLOBAL`) VALUES ('FACTOR1_GLOBAL_MARKET_POSITION', 'STEP_7', '1|2|3|4|5|6|7|8', 'RADIO', null, 0, 1);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `GLOBAL`) VALUES ('FACTOR4_FINANCIAL_POLICIES', 'STEP_8', '1|2|3|4|5|6|7|8', 'RADIO', null, 0, 1);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`, `GLOBAL`) VALUES ('FACTOR5_BUSINESS_RISK_PROFILE', 'STEP_9', '1|2|3|4|5|6|7|8', 'RADIO', null, 0, 1);

INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('TEST_INT', 'STEP_B', '0', 'NUM', null, 0);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('TEST_DROP', 'STEP_B', '1|23|43|100', 'DROP_DOWN', null, 10);
INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('TEST_DATE', 'STEP_B', '', 'TIME', null, 20);



-- INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('TEST_INT', 'STEP_B', '0', 'NUM', null, 0);
-- INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('TEST_DROP', 'STEP_B', '1|23|43|100', 'DROP_DOWN', null, 10);
-- INSERT INTO `rating`.`RATING_TYPE` (`NAME`, `STEP`, `DEFAULT_VALUE`, `TYPE_VALUE`, `SECTOR`, `ORDER`) VALUES ('TEST_DATE', 'STEP_B', '', 'TIME', null, 20);
